apiVersion: v2
appVersion: 1.9.7
description: |
  All-in-one secure chat app for teams, friends and organisations.
  Keeps conversations in your control, safe from data-mining and ads.
  Talk to everyone through the open global Matrix network, protected by proper
  end-to-end encryption.
icon: https://element.io/images/element-logo.svg
maintainers:
- email: ace@haxalot.com
  name: Alexander Olofsson
name: element-web
type: application
version: 1.0.42
