---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: peertube-data
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: my-block-storage-retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: my-block-storage-retain