
replicaCount: 1
image:
  repository: vectorim/element-web
  pullPolicy: IfNotPresent
  # tag: ""
imagePullSecrets: []
# nameOverride: ""
# fullnameOverride: ""

defaultServer:
  url: 'https://matrix.example.com'
  name: 'matrix.example.com'
  # identity_url: 'https://vector.im'

config: {"sso_immediate_redirect":"true"}
# https://github.com/vector-im/element-web/pull/19437
# This option is being deprecated imminently and replaced with:
# {"sso_redirect_options":{"immediate":"true"}}

extraVolumes: {}
# - name: backgrounds
#   persistentVolumeClaim:
#     claimName: element-backgrounds
extraVolumeMounts: {}
# - name: backgrounds
#   mountPath: /app/themes/element/img/backgrounds/

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-example"
    cert-manager.io/acme-challenge-type: http01
  hosts:
    - element.example.com
  tls:
   - secretName: example-element-tls
     hosts:
       - element.example.com

resources:
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector:
  my.provider.com/node-pool: matrix
tolerations: []
affinity: {}
